import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { ThemeProvider } from "../context/ThemeProvider";

export const metadata: Metadata = {
  title: "SaarthiGenAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
      <link
  rel="icon"
  href={`data:image/svg+xml,${encodeURIComponent(
    `<svg fill="none" height="50" viewBox="0 0 32 32" width="50" xmlns="http://www.w3.org/2000/svg">
      <path
        clip-rule="evenodd"
        d="M26.6482 7.0205L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 10.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z"
        fill="currentColor"
        fill-rule="evenodd"
      />
    </svg>`
  )}`}
  type="image/svg+xml"
/>
        <link rel="alternate icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body>
        <ThemeProvider>
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}

